[package]
name = "shellexec"
version.workspace = true
authors.workspace = true
edition.workspace = true
description = "Cross-platform shellcode executor in rwx memory"
readme = "../README.md"
repository.workspace = true
license.workspace = true
keywords = ["shellcode", "shellcode-loader"]
categories = ["command-line-utilities", "memory-management"]

[dependencies]
anyhow.workspace = true
argh.workspace = true
virtual-memory.workspace = true
