[package]
name = "virtual-memory"
version.workspace = true
authors.workspace = true
edition.workspace = true
description = "Library for allocating RWX memory on Unix and Windows"
repository.workspace = true
license.workspace = true
keywords = ["virtual-memory", "rwx", "rwx-memory"]
categories = ["memory-management", "api-bindings", "no-std"]

[target.'cfg(unix)'.dependencies]
libc.workspace = true

[target.'cfg(windows)'.dependencies]
windows-sys.workspace = true
